// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// EchoRouter is an autogenerated mock type for the EchoRouter type
type EchoRouter struct {
	mock.Mock
}

type EchoRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *EchoRouter) EXPECT() *EchoRouter_Expecter {
	return &EchoRouter_Expecter{mock: &_m.Mock}
}

// GET provides a mock function with given fields: path, h, m
func (_m *EchoRouter) GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path, h)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GET")
	}

	var r0 *echo.Route
	if rf, ok := ret.Get(0).(func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route); ok {
		r0 = rf(path, h, m...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Route)
		}
	}

	return r0
}

// EchoRouter_GET_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GET'
type EchoRouter_GET_Call struct {
	*mock.Call
}

// GET is a helper method to define mock.On call
//   - path string
//   - h echo.HandlerFunc
//   - m ...echo.MiddlewareFunc
func (_e *EchoRouter_Expecter) GET(path interface{}, h interface{}, m ...interface{}) *EchoRouter_GET_Call {
	return &EchoRouter_GET_Call{Call: _e.mock.On("GET",
		append([]interface{}{path, h}, m...)...)}
}

func (_c *EchoRouter_GET_Call) Run(run func(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)) *EchoRouter_GET_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]echo.MiddlewareFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(echo.MiddlewareFunc)
			}
		}
		run(args[0].(string), args[1].(echo.HandlerFunc), variadicArgs...)
	})
	return _c
}

func (_c *EchoRouter_GET_Call) Return(_a0 *echo.Route) *EchoRouter_GET_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EchoRouter_GET_Call) RunAndReturn(run func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route) *EchoRouter_GET_Call {
	_c.Call.Return(run)
	return _c
}

// NewEchoRouter creates a new instance of EchoRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEchoRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *EchoRouter {
	mock := &EchoRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
